/**
 * Prompt Builder — assembles generation prompts using fixed templates.
 *
 * Key principle: character appearance and scene environment are FIXED template
 * strings, never re-generated by LLM. LLM only provides action/emotion/composition.
 * This eliminates prompt drift across shots.
 *
 * Different prompt assembly per strategy type:
 * - C (cross-scene): full prompt (style + scene + all characters + action + camera)
 * - A1 (continuous): minimal (character anchors + action only, frame ref carries scene)
 * - A2 (angle change): medium (scene keywords + characters + action + camera)
 * - B/D segments: first segment = full, continuation = motion-only
 */
import type { Shot, Scene, Character, ShotStrategy } from "../types";
import type { StyleProfile } from "../types/project";

/**
 * Build a fixed character appearance template string.
 * This is NEVER regenerated by LLM — it's a mechanical concatenation.
 */
export function buildCharacterTemplate(char: Character): string {
  return `${char.name}: ${char.visual_description}`;
}

/**
 * Build a fixed scene environment template string.
 */
export function buildSceneTemplate(scene: Scene): string {
  return `${scene.description}, ${scene.lighting} lighting, ${scene.time_of_day}, ${scene.weather}, ${scene.mood} atmosphere`;
}

/**
 * Assemble the final generation prompt for a shot based on its strategy.
 */
export function assemblePrompt(
  shot: Shot,
  strategy: ShotStrategy,
  characters: Character[],
  scene: Scene | undefined,
  style: StyleProfile,
  segmentIndex?: number,
): string {
  const shotChars = characters.filter((c) =>
    shot.character_ids.includes(c.character_id),
  );

  const charTemplates = shotChars.map(buildCharacterTemplate).join(". ");
  const sceneTemplate = scene ? buildSceneTemplate(scene) : "";
  const styleStr = [style.visual_style, style.color_tone].filter(Boolean).join(", ");
  const cameraStr = shot.camera_movement !== "static" ? `, ${shot.camera_movement} camera` : "";
  const emotionStr = shot.emotion_tag !== "neutral" ? `, ${shot.emotion_tag} mood` : "";

  // For B/D continuation segments (not the first)
  if (segmentIndex != null && segmentIndex > 0) {
    return buildContinuationPrompt(shot, shotChars, cameraStr);
  }

  switch (strategy.strategy_type) {
    case "C":
    case "D":
      // Full prompt — model has no prior visual context
      return buildFullPrompt(styleStr, sceneTemplate, charTemplates, shot, cameraStr, emotionStr);

    case "A1":
      // Minimal — frame reference carries scene context
      return buildMinimalPrompt(charTemplates, shot, cameraStr);

    case "A2":
      // Medium — scene keywords + characters + action
      return buildMediumPrompt(sceneTemplate, charTemplates, shot, cameraStr, emotionStr);

    case "B":
      // First segment gets full prompt
      return buildFullPrompt(styleStr, sceneTemplate, charTemplates, shot, cameraStr, emotionStr);

    default:
      return buildFullPrompt(styleStr, sceneTemplate, charTemplates, shot, cameraStr, emotionStr);
  }
}

/** C-type / D-first / B-first: everything spelled out */
function buildFullPrompt(
  style: string,
  scene: string,
  chars: string,
  shot: Shot,
  camera: string,
  emotion: string,
): string {
  const parts: string[] = [];
  if (style) parts.push(style);
  if (scene) parts.push(scene);
  if (chars) parts.push(chars);
  parts.push(`${shot.shot_type} shot`);
  parts.push(shot.action_description);
  if (camera) parts.push(camera.replace(/^, /, ""));
  if (emotion) parts.push(emotion.replace(/^, /, ""));
  if (shot.dialogue) parts.push(`dialogue: "${shot.dialogue}"`);
  return parts.join(". ") + ".";
}

/** A1-type: frame ref carries scene, just describe the action */
function buildMinimalPrompt(
  chars: string,
  shot: Shot,
  camera: string,
): string {
  const parts: string[] = [];
  if (chars) parts.push(chars);
  parts.push(shot.action_description);
  if (camera) parts.push(camera.replace(/^, /, ""));
  return parts.join(". ") + ".";
}

/** A2-type: scene keywords + characters + action */
function buildMediumPrompt(
  scene: string,
  chars: string,
  shot: Shot,
  camera: string,
  emotion: string,
): string {
  const parts: string[] = [];
  if (scene) parts.push(scene);
  if (chars) parts.push(chars);
  parts.push(`${shot.shot_type} shot`);
  parts.push(shot.action_description);
  if (camera) parts.push(camera.replace(/^, /, ""));
  if (emotion) parts.push(emotion.replace(/^, /, ""));
  return parts.join(". ") + ".";
}

/** B/D continuation segments: motion-only, very restrained */
function buildContinuationPrompt(
  shot: Shot,
  chars: Character[],
  camera: string,
): string {
  const charAnchors = chars.map((c) => c.name).join(", ");
  const parts: string[] = [];
  if (charAnchors) parts.push(charAnchors);
  parts.push(`continue the motion: ${shot.action_description}`);
  if (camera) parts.push(camera.replace(/^, /, ""));
  return parts.join(". ") + ".";
}
